
const LATEST_POSTS = [
  { cat: "course00", item: "k03", date: "2026년 8월 27일",
    summary: "Claude Code의 에이전틱 루프, 설치, 워크플로우, 컨텍스트 관리, 코드 리뷰, 커스터마이징을 정리했습니다." },
  { cat: "project00", item: "g02", date: "2026년 8월 20일",
    summary: "GoToAiNative 프로젝트의 진행 상황과 다음 단계를 기록합니다." },
  { cat: "note00", item: "f08", date: "2026년 8월 12일",
    summary: "Claude의 활용 방법에 대한 정보들을 모아놓았습니다." },
];

const CATEGORIES = [
  // ── A00 : 뉴스/타임라이 ────────────────────────────────────────────────────
  {
    id: "a00",
    folder: "A_뉴스_타임라인",
    label: "뉴스 타임라인",
    icon: "rss",
    description: "AI 트렌드, 로보틱스, 소형 언어모델 등 최신 동향을 시간순으로 기록합니다.",
    items: [
      { id: "e01", title: "AI시대 생존전략", meta: "E01", hue: 5,
        body: "AI시대를 주도하는 실리콘밸리 엔지니어의 생존공식" },
      { id: "e02", title: "Karpathy LLM", meta: "E04", hue: 5,
        body: "Andrej Karpathy가 제안한 \"LLM을 활용한 개인 지식 베이스 구축 패턴\"입니다." },
      { id: "e03", title: "AI로보틱스", meta: "E03", hue: 5,
        body: "AI로보틱스에 대한 내용을 준비 중입니다." },
      { id: "e04", title: "소형언어모델", meta: "E04", hue: 5,
        body: "소형언어모델에 대한 내용을 준비 중입니다." },
      { id: "e05", title: "Langfuse-guide", meta: "E05", hue: 5,
        body: "Langfuse 설치 및 사용 가이드 (Docker 기반)" },
      { id: "e06", title: "LangChain vs Pure Python", meta: "E06", hue: 5,
        body: " LLM Fallback 메커니즘 완벽 가이드 (LangChain vs Pure Python)." },
      { id: "e07", title: "Speed-Metrics-Guide", meta: "E07", hue: 5,
        body: "LLM 속도 파헤쳐보기 (TTFT, TPOT, Throughput 개념)." },
      { id: "e08", title: "GPU-Monitoring-Guide", meta: "E08", hue: 5,
        body: "NVIDIA GPU 모니터링 완벽 가이드 (정의, 구성요소, 실습)." },
      { id: "e09", title: "Server-ops-guide", meta: "E09", hue: 5,
        body: "개발자를 위한 AI 서버 관리 꿀팁 A to Z (screen, git, Postman)." },
    ],
  },
  
 
  // ── B00 : 노트 ────────────────────────────────────────────────────────────
  {
    id: "b00",
    folder: "B_노트",
    label: "노트",
    icon: "edit-3",
    description: "짧은 메모와 생각을 빠르게 기록합니다.",
    items: [
      { id: "b01", title: "프롬프팅", meta: "B01", hue: 40,
        skipGenerate: true,
        body: "프롬프팅 관련한 예제들을 모아 놓았습니다." },
      { id: "b02", title: "Skill References", meta: "B02", hue: 40,
        skipGenerate: true,
        body: "유용한 Skill들을 모아가기 위한 용도 입니다" },
      { id: "b03", title: "Skill Description", meta: "B03", hue: 40,
        skipGenerate: true,
        body: "Skill 정보들에 대해 설명을 제공하기 위한 용도 입니다." },
      { id: "b04", title: "MCP_Connector Reference", meta: "B04", hue: 40,
        skipGenerate: true,
        body: "유용한 MCP_Connector들 정보를 모아가기 위한 용도 입니다." },
      { id: "b05", title: "MCP_Connector Description", meta: "B05", hue: 40,
        skipGenerate: true,
        body: "MCP, Connector 정보들에 대해 설명을 제공하기 위한 용도 입니다." },
      { id: "b06", title: "디자인 노트", meta: "B06", hue: 40,
        skipGenerate: true,
        body: "디자인 관련하여 정보들을 모아놓았습니다." },
      { id: "b07", title: "영상_미디어", meta: "B07", hue: 40,
        skipGenerate: true,
        body: "영상·미디어 관련하여 정보들을 모아놓았습니다." },
      { id: "b08", title: "Claude 활용", meta: "B08", hue: 40,
        skipGenerate: true,
        body: "Claude의 활용 방법에 대한 정보들을 모아놓았습니다." },
      { id: "b10", title: "아이디어 스케치", meta: "B10", hue: 40,
        skipGenerate: true,
        body: "떠오르는 대로 적어둔 초기 아이디어 메모입니다." },
      { id: "b11", title: "교육_강좌 사이트", meta: "B11", hue: 40,
        skipGenerate: true,
        body: "교육·강좌 관련하여 참고할만한 사이트들을 모아놓았습니다." },
      { id: "b12", title: "기타 참고 사이트", meta: "B12", hue: 40,
        skipGenerate: true,
        body: "그 외 기타 참고할만한 사이트들에 대한 정보들을 모아놓았습니다." },
    ],
  },

  // ── C00 : 프로젝트 (Projects) ────────────────────────────────────────────────────────
  {
    id: "c00",
    folder: "C_프로젝트",
    label: "프로젝트",
    icon: "folder",
    description: "MyWiki, GoToAiNative 등 진행 중인 개인 프로젝트를 관리합니다.",
    items: [
      { id: "g01", title: "MyWiki프로젝트", meta: "G01", hue: 265,
        body: "MyWiki프로젝트에 대한 내용을 준비 중입니다." },
      { id: "g02", title: "GoToAiNative", meta: "G02", hue: 265,
        body: "GoToAiNative에 대한 내용을 준비 중입니다." },
      { id: "g03", title: "주식프로젝트", meta: "G03", hue: 265,
        body: "과거 History 및 패턴 분석을 통한 주식 매매 프로그램 입니다." },
      { id: "g04", title: "영상프로젝트", meta: "G04", hue: 265,
        body: "영상프로젝트에 대한 내용 입니다." },
    ],
  },

  
  // ── 최신 뉴스 (Latest News) ───────────────────────────────────────────
  {
    id: "d00",
    folder: "D_학습자료",
    label: "학습자료",
    icon: "rss",
    description: "AI 업계 최신 소식과 눈여겨볼 뉴스를 시간순으로 기록합니다.",
    items: [
      { id: "d01", title: "MyWiki프로젝트", meta: "D01", hue: 265,
        body: "MyWiki프로젝트에 대한 내용을 준비 중입니다." },
      { id: "d02", title: "GoToAiNative", meta: "D02", hue: 265,
        body: "GoToAiNative에 대한 내용을 준비 중입니다." },
      { id: "d03", title: "주식프로젝트", meta: "D03", hue: 265,
        body: "과거 History 및 패턴 분석을 통한 주식 매매 프로그램 입니다." },
      { id: "d04", title: "영상프로젝트", meta: "D04", hue: 265,
        body: "영상프로젝트에 대한 내용 입니다." },
    ],
  },

